#!/usr/bin/env bash
#
# Regenerate constraints.txt — the CI dependency lock — by resolving the project
# in a CLEAN virtualenv, RUNNING THE TEST SUITE, and only then freezing the
# verified ("green") closure. This guarantees the lock is a set of versions the
# suite actually passes on, rather than "whatever PyPI resolves to latest"
# (which is exactly what broke CI the first time).
#
# Run in an environment WITH network/PyPI access (NOT the Claude sandbox):
#
#     ./scripts/lock-deps.sh
#     PYBIN=python3.11 ./scripts/lock-deps.sh   # lock on the matrix floor
#
# Notes:
#   * The lock resolves against the Python that runs it. CI is a 3.11–3.13
#     matrix; generate on the FLOOR (3.11) for the widest compatibility. For a
#     true cross-version lock, migrate to `uv lock` / `uv pip compile
#     --universal` later (a clean upgrade from this pip-freeze approach).
#   * If the test step fails, NO lock is written — fix/pin the offending dep and
#     re-run, so a red environment can never be locked.
#
set -euo pipefail
cd "$(dirname "$0")/.."

PYBIN="${PYBIN:-python3}"
EXTRAS="dev,dashboard,a2a,metrics,persistence"
VENV="$(mktemp -d)/lockenv"

echo ">> Creating clean venv with ${PYBIN} at ${VENV}"
"${PYBIN}" -m venv "${VENV}"
# shellcheck disable=SC1091
source "${VENV}/bin/activate"
python -m pip install --quiet --upgrade pip

echo ">> Installing project + extras (resolving fresh from PyPI) ..."
pip install -e ".[${EXTRAS}]"

echo ">> Verifying the resolved env is GREEN before locking ..."
pytest tests/ -q --ignore=tests/test_e2e_stress.py

echo ">> Freezing the verified closure -> constraints.txt"
{
  echo "# CI dependency lock — generated by scripts/lock-deps.sh from a GREEN env."
  echo "# Do not hand-edit; re-run the script to regenerate. ($(python --version 2>&1))"
  pip freeze --exclude-editable | sort
} > constraints.txt

deactivate
echo ">> Done. Review 'git diff constraints.txt' and commit."
